languageCode = "fr-fr"
title = "Site de la Fun"
theme = "hugo-flex"


[menu]
  [[menu.main]]
    identifier = "LaFun"
    name = "LaFun"
    url = "/LaFun/lafun"
    weight = 1
  [[menu.main]]
    identifier = "LaFun-lafun"
    name = "La F.U.N"
    url = "/LaFun/LaFun"
    parent = "LaFun"
    weight = 1
  [[menu.main]]
    identifier = "LaFun-autrebrique"
    name = "L'Autre Brique"
    url = "/LaFun/autreBrique"
    parent = "LaFun"
    weight = 2
  [[menu.main]]
    identifier = "LaFun-funlab"
    name = "Le Fun Lab"
    url = "/LaFun/funLab"
    parent = "LaFun"
    weight = 3
  [[menu.main]]
    identifier = "LaFun-ateliersLaboratoires"
    name = "Les Ateliers Laboratoires"
    url = "/LaFun/ateliersLaboratoires"
    parent = "LaFun"
    weight = 4
  [[menu.main]]
    identifier = "LaFun-interZone"
    name = "InterZone"
    url = "/LaFun/interZone"
    parent = "LaFun"
    weight = 5
  [[menu.main]]
    identifier = "Projets"
    name = "Projets"
    url = "/projets"
    weight = 2
  [[menu.main]]
    identifier = "actualites"
    name = "Actualités"
    url = "/actualites"
    weight = 3
  [[menu.main]]
    identifier = "agenda"
    name = "Agenda"
    url = "/Agenda"
    weight = 4
  [[menu.main]]
    identifier = "ressources"
    name = "Ressources"
    url = "/Ressources"
    weight = 5
  [[menu.main]]
    identifier = "ressources-communaute"
    name = "Communaute"
    url = "/Ressources/communaute"
    parent = "ressources"
    weight = 1
  [[menu.main]]
    identifier = "wiki"
    name = "Wiki de la F.U.N"
    url = "/Ressources/wiki"
    parent = "ressources"
    weight = 2
  [[menu.main]]
    identifier = "documentations"
    name = "Documentations"
    url = "/Ressources/doc"
    parent = "ressources"
    weight = 3
  [[menu.main]]
    identifier = "infos"
    name = "Infos"
    url = "/Ressources/infos"
    parent = "ressources"
    weight = 4
  [[menu.main]]
    identifier = "contacts"
    name = "Contacts"
    url = "/Ressources/contacts"
    parent = "ressources"
    weight = 5
  [[menu.main]]
    identifier = "carte"
    name = "Carte"
    url = "/Ressources/carte"
    parent = "ressources"
    weight = 6
  [[menu.main]]
    identifier = "NousRejoindre"
    name = "Nous Rejoindre"
    url = "/NousRejoindre"
    weight = 6



[taxonomies]
  tag = "tags"
  category = "categories"
  structure = "structures"
  group = "groups"