languageCode = "fr-fr"
title = "Site de la Fun"
theme = "hugo-flex"



[menu]
  [[menu.main]]
    identifier = "Association"
    name = "Association"
    url = "/Association/lafun"
    weight = 1
  [[menu.main]]
    identifier = "association-lafun"
    name = "La F.U.N"
    url = "/Association/LaFun"
    parent = "Association"
    weight = 1
  [[menu.main]]
    identifier = "association-autrebrique"
    name = "L'Autre Brique"
    url = "/Association/autreBrique"
    parent = "Association"
    weight = 2
  [[menu.main]]
    identifier = "association-funlab"
    name = "Le Fun Lab"
    url = "/Association/funLab"
    parent = "Association"
    weight = 3
  [[menu.main]]
    identifier = "association-ateliersLaboratoires"
    name = "Les Ateliers Laboratoires"
    url = "/Association/ateliersLaboratoires"
    parent = "Association"
    weight = 4
  [[menu.main]]
    identifier = "association-interZone"
    name = "InterZone"
    url = "/Association/interZone"
    parent = "Association"
    weight = 5
  [[menu.main]]
    identifier = "Projets"
    name = "Projets"
    url = "/projets"
    weight = 2
  [[menu.main]]
    identifier = "actualites"
    name = "Actualités"
    url = "/actualites"
    weight = 3
  [[menu.main]]
    identifier = "agenda"
    name = "Agenda"
    url = "/Agenda"
    weight = 4
  [[menu.main]]
    identifier = "ressources"
    name = "Ressources"
    url = "/Ressources"
    weight = 5
  [[menu.main]]
    identifier = "ressources-communaute"
    name = "Communaute"
    url = "/Ressources/communaute"
    parent = "ressources"
    weight = 1
  [[menu.main]]
    identifier = "wiki"
    name = "Wiki de la F.U.N"
    url = "/Ressources/wiki"
    parent = "ressources"
    weight = 2
  [[menu.main]]
    identifier = "documentations"
    name = "Documentations"
    url = "/Ressources/doc"
    parent = "ressources"
    weight = 3
  [[menu.main]]
    identifier = "infos"
    name = "Infos"
    url = "/Ressources/infos"
    parent = "ressources"
    weight = 4
  [[menu.main]]
    identifier = "contacts"
    name = "Contacts"
    url = "/Ressources/contacts"
    parent = "ressources"
    weight = 5
  [[menu.main]]
    identifier = "carte"
    name = "Carte"
    url = "/Ressources/carte"
    parent = "ressources"
    weight = 6
  [[menu.main]]
    identifier = "NousRejoindre"
    name = "Nous Rejoindre"
    url = "/NousRejoindre"
    weight = 6



[taxonomies]
  tag = "tags"
  category = "categories"
  structure = "structures"