languageCode = "fr-fr"
title = "Site de la Fun"
theme = "hugo-flex"



[menu]
  [[menu.main]]
    identifier = "acceuil"
    name = "Acceuil"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "presentations"
    name = "Presentations"
    url = "/presentations"
    weight = 2
  [[menu.main]]
    identifier = "presentation-lafun"
    name = "La F.U.N"
    url = "/presentations/laFun"
    parent = "presentations"
    weight = 1
  [[menu.main]]
    identifier = "presentation-autrebrique"
    name = "L'Autre Brique"
    url = "/presentations/autreBrique"
    parent = "presentations"
    weight = 2
  [[menu.main]]
    identifier = "presentation-funlab"
    name = "Le Fun Lab"
    url = "/presentations/funLab"
    parent = "presentations"
    weight = 3
  [[menu.main]]
    identifier = "presentation-preciouskitchen"
    name = "Precious Kitchen"
    url = "/presentations/preciousKitchen"
    parent = "presentations"
    weight = 4
  [[menu.main]]
    identifier = "actualites"
    name = "Actualités"
    url = "/actualites"
    weight = 3
  [[menu.main]]
    identifier = "agenda"
    name = "Agenda"
    url = "/agenda"
    weight = 4
  [[menu.main]]
    identifier = "communaute"
    name = "Communauté"
    url = "/communaute"
    weight = 5
  [[menu.main]]
    identifier = "ressources"
    name = "Ressources"
    url = "/ressources"
    weight = 6
  [[menu.main]]
    identifier = "wiki"
    name = "Wiki de la F.U.N"
    url = "/wiki"
    parent = "ressources"
    weight = 1
  [[menu.main]]
    identifier = "documentations"
    name = "Documentations"
    url = "/documentations"
    parent = "ressources"
    weight = 2
  [[menu.main]]
    identifier = "infos"
    name = "Infos"
    url = "/infos"
    parent = "ressources"
    weight = 3
  [[menu.main]]
    identifier = "contacts"
    name = "Contacts"
    url = "/contacts"
    parent = "ressources"
    weight = 4
  [[menu.main]]
    identifier = "carte"
    name = "Carte"
    url = "/carte"
    weight = 7


[taxonomies]
  tag = "tags"
  category = "categories"
  structure = "structures"