backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "Actualites" # Used in routes, e.g., /admin/collections/blog
    label: "Actualites" # Used in the UI
    slug: "{{day}}-{{month}}-{{year}}_{{slug}}"    
    folder: "/content/Actualites" # The path to the folder where the documents are stored
    path: '{{slug}}/index.md'
    create: true # Allow users to create new documents in this collection
    media_folder: "images/" # Media files will be stored in the same folder
    public_folder: "images/" # The src attribute for uploaded media will begin with relative path
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Auteur", name: "author", widget: "select", options: ["Cat", "Fab'Manager", "Julie"]}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Date de l'évenement", name: "_date", widget: "datetime"}
      - {label: "Tarif de l'évenement", name: "_tarif", widget: "string"}
      - {label: 'Couleur', name: 'color', widget: 'color' }
      - {label: "Present dans l'agenda", name: "_agenda", widget: "boolean", default: false}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
