backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

locale: 'fr'

# This line should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "Actualites" # Used in routes, e.g., /admin/collections/blog
    label: "Actualites" # Used in the UI
    slug: "{{slug}}"    
    folder: "/content/Actualites" # The path to the folder where the documents are stored
    path: '{{slug}}/index'
    create: true # Allow users to create new documents in this collection
    media_folder: "images/" # Media files will be stored in the same folder
    public_folder: "images/" # The src attribute for uploaded media will begin with relative path
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Auteur", name: "author", widget: "select", options: ["Cat", "Fab'Manager", "Julie"]}
      - {label: "Date", name: "date", widget: "datetime", format: "DD/MM/YYYY"}
      - {label: "Date de publication", name: "publishDate", widget: "datetime", format: "DD/MM/YYYY"}
      - {label: "Date de l'évenement", name: "eventDate", widget: "datetime", format: "DD/MM/YYYY"}
      - {label: "Tarif de l'évenement", name: "_tarif", widget: "string"}
      - {label: 'Couleur', name: 'color', widget: 'color' }
      - {label: "Present dans l'agenda", name: "presenceAgenda", widget: "boolean", default: false}
      - {label: "Vignette", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name : "Presentations"
    label: "Presentations"
    slug: "{{slug}}"
    folder: "/content/LaFun"
    path: '{{dir}}/texts/{{slug}}'
    create: true
    summary: "Presentation '{{dir}}' - {{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string", required: true}
      - {label: "Dossier", name: "dir", widget: "select", options: ["LaFun","FunLab", "AutreBrique"], required: true}
      - {label: "Corps", name: "body", widget: "markdown", required: true}
  - name : "Projets"
    label: "Projets"
    slug: "{{slug}}"
    folder: "/content/Projets"
    path: '{{dir}}/texts/{{slug}}'
    create: true
    summary: "Projet '{{dir}}' - {{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string", required: true}
      - {label: "Dossier", name: "dir", widget: "select", options: ["LaFun","FunLab", "AutreBrique"], required: true}
      - {label: "Corps", name: "body", widget: "markdown", required: true}
  - name : "Tags"
    label: "Liste des tags"
    folder: "/content/tags"
    path: '{{title}}/index'
    create: true
    summary: "Projet '{{title | upper}}' - {{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string", required: true, pattern: ["a-z", "Le titre ne doit pas comporter autre chose que des minuscules"]}
      - {label: "Description", name: "body", widget: "markdown", required: true}