backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

locale: 'fr'


# This line should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "Actualites" # Used in routes, e.g., /admin/collections/blog
    label: "Actualites" # Used in the UI
    slug: "{{slug}}"    
    folder: "/content/Actualites" # The path to the folder where the documents are stored
    path: "{{eventDate | date('YYYY')}}/{{eventDate | date('MM')}}/{{eventDate | date('DD')}}{{slug}}/index"
    filter: {field: "visible", value: true}
    create: true # Allow users to create new documents in this collection
    media_folder: "images/" # Media files will be stored in the same folder
    public_folder: "images/" # The src attribute for uploaded media will begin with relative path
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "relation", collection: "Tags", search_fields: ["title"], value_field: "title", multiple: true, options_length: 5}
      - {label: "Auteur", name: "author", widget: "select", options: ["Cat", "Fab'Manager", "Julie"]} #repère ACTU01
      - {label: "Date de l'evenement", name: "eventDate", widget: "datetime"}
      - {label: "Date de publication", name: "publishDate", widget: "datetime"}
      - {label: "Durée", name: "duration", widget: "number", required: false}
      - {label: "Tarif de l'évenement", name: "_tarif", widget: "string"}
      - {label: "Present dans l'agenda", name: "presenceAgenda", widget: "boolean", default: false}
      - {label: "Lien de l'article mère", name: "motherLink", widget: "string", default: "", required: false}
      - {label: "Present dans les actualites", name: "presenceActualites", widget: "boolean", default: true}
      - {label: "Jeune public", name: "youngFriendly", widget: "boolean", default: true, required: false}
      - {label: "Vignette", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "partenaires", name: "partenaires", widget: "relation", collection: "Partenaires", search_fields: ["name"], value_field: "name", multiple: true, required: false}
      - {label: "visible", name: "visible", widget: "string", hidden: true, default: true}
  - name : "Presentations"
    label: "Presentations"
    slug: "{{slug}}"
    folder: "/content/LaFun"
    path: '{{dir}}/texts/{{slug}}'
    filter: {field: "visible", value: true}
    media_folder: "images/" # Media files will be stored in the same folder
    public_folder: "images/" # The src attribute for uploaded media will begin with relative path
    create: true
    summary: "'{{fields.dir}}' > {{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string", required: true}
      - {label: "Dossier", name: "dir", widget: "select", options: ["LaFun","FunLab", "AutreBrique"], required: true} #repère PRES01
      - {label: "Logo", name: "logo", widget: "image", required: false}
      - {label: "Corps", name: "body", widget: "markdown", required: true}
      - {label: "visible", name: "visible", widget: "string", hidden: true, default: true}
  - name : "Projets"
    label: "Projets"
    slug: "{{slug}}"
    folder: "/content/Projets"
    path: '{{dir}}/texts/{{slug}}'
    filter: {field: "visible", value: true}
    media_folder: "images/" # Media files will be stored in the same folder
    public_folder: "images/" # The src attribute for uploaded media will begin with relative path
    create: true
    summary: "Projet '{{dir}}' - {{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string", required: true}
      - {label: "Dossier", name: "dir", widget: "select", options: ["Projet1","Projet2", "Projet3"], required: true}
      - {label: "Vignette", name: "thumbnail", widget: "image"}
      - {label: "Corps", name: "body", widget: "markdown", required: true}
      - {label: "visible", name: "visible", widget: "string", hidden: true, default: true}
  - name : "Tags"
    label: "Liste des tags"
    filter: {field: "visible", value: true}
    folder: "/content/tags"
    path: '{{title}}/_index'
    create: true
    summary: "Tag '{{title | upper}}' - {{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string", required: true, pattern: ["[a-z0-9]", "Le titre ne doit comporter que des minuscules ou des chiffres"]}
      - {label: "Groupe", name: "group", widget: "select", options: ["Activité","Projet", "Mot-clé"], required: true}
      - {label: "Description", name: "body", widget: "markdown", required: true}
      - {label: "visible", name: "visible", widget: "string", hidden: true, default: true}
  - name: "Partenaires"
    label: "Partenaires"
    label_singular: 'Partenaire'
    folder: content/Partenaires
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    media_folder: "images/" # Media files will be stored in the same folder
    fields:
      - {label: "Nom", name: "name", widget: "string", required: true}
      - {label: "Logo", name: "logo", widget: "image", required: true}
      - {label: "visible", name: "visible", widget: "string", hidden: true, default: true}
    # adding a nested object will show the collection folder structure
  - label: "Pages"
    name: "pages"
    files: 
      - label : "RGPD"
        name : "RGPD"
        file: "content/rgpd/_index.md"
        fields:
          - {label: "text", name: "body", widget: "markdown", required: true}
          - {label: "visible", name: "visible", widget: "string", hidden: true, default: true}
      - label : "mentions_legales"
        name : "mentions_legales"
        file: "content/mentions_legales/_index.md"
        fields:
          - {label: "text", name: "body", widget: "markdown", required: true}
          - {label: "visible", name: "visible", widget: "string", hidden: true, default: true}
      - label : "newsletter"
        name : "newsletter"
        file: "content/newsletter/_index.md"
        fields:
          - {label: "text", name: "body", widget: "markdown", required: true}
          - {label: "visible", name: "visible", widget: "string", hidden: true, default: true}
